---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app network-ups-tools
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      nut:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/jr0dd/network-ups-tools
              tag: v2.8.1@sha256:2a6e47d431cbb901482ad6692f089a7541524fd3538e42857b39663bb331ba25
            env:
              TZ: "Europe/London"
            securityContext:
              privileged: true
        pod:
          annotations:
            configmap.reloader.stakater.com/reload: network-ups-tools-config
          nodeSelector:
            ups.feature.node.kubernetes.io/apc: "true"
    service:
      app:
        controller: nut
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: ${SVC_NUT_IP}
        externalTrafficPolicy: Cluster
        ports:
          http:
            port: 3493
          metrics:
            enabled: true
            port: 9199
    persistence:
      config:
        type: configMap
        name: network-ups-tools-config
        defaultMode: 0400
        globalMounts:
          - path: /etc/nut
      ups:
        type: hostPath
        hostPath: /dev/usb/hiddev0
        globalMounts:
          - path: /dev/usb/hiddev0
            readOnly: false

    configMaps:
      config:
        enabled: true
        data:
          nut.conf: |-
            MODE=netserver

          upsd.conf: |-
            MAXAGE 20
            LISTEN 0.0.0.0
            LISTEN ::

          ups.conf: |-
            [apcups]
              driver = usbhid-ups
              port = hiddev0
              desc = "APC Back-UPS ES 650G2"
              pollinterval = 10

          upsd.users: |-
            [upsmon]
              password  = "password"
              actions = SET
              instcmds = ALL
              upsmon primary

