---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app network-ups-tools
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  install:
    remediation:
      retries: 3

  upgrade:
    remediation:
      retries: 3

  values:
    image:
      repository: ghcr.io/jr0dd/network-ups-tools
      tag: v2.8.1@sha256:7999ff0ed6f4e31d64f8a6afc66dce26e147608c9d595f4f4fb7b4a6e442ae00
    controller:
      strategy: RollingUpdate

    env:
      TZ: "Europe/London"

    securityContext:
      privileged: true

    service:
      main:
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: ${SVC_NUT_IP}
        externalTrafficPolicy: Cluster
        ports:
          http:
            port: 3493
            protocol: TCP

      metrics:
        enabled: true
        ports:
          metrics:
            enabled: true
            port: 9199
            protocol: TCP

    persistence:
      config:
        enabled: true
        type: configMap
        name: &config network-ups-tools-config
        mountPath: /etc/nut
        defaultMode: 256
      ups:
        enabled: true
        type: hostPath
        hostPath: /dev/usb/hiddev0
        mountPath: /dev/usb/hiddev0
        readOnly: false

    configMaps:
      config:
        enabled: true
        data:
          nut.conf: |-
            MODE=netserver

          upsd.conf: |-
            MAXAGE 20
            LISTEN 0.0.0.0
            LISTEN ::

          ups.conf: |-
            [apcups]
              driver = usbhid-ups
              port = hiddev0
              desc = "APC Back-UPS ES 650G2"
              pollinterval = 10

          upsd.users: |-
            [upsmon]
              password  = "password"
              actions = SET
              instcmds = ALL
              upsmon primary

    podAnnotations:
      configmap.reloader.stakater.com/reload: *config

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: ups.feature.node.kubernetes.io/apc
                  operator: In
                  values:
                    - "true"
