---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app actual
spec:
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    controllers:
      actual:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/actualbudget/actual-server
              tag: 25.8.0
            env:
              TZ: "Europe/London"
              PORT: &port 5006
              TINI_SUBREAPER: 1
              ACTUAL_NORDIGEN_SECRET_ID: "${ACTUAL_NG_ID}"
              ACTUAL_NORDIGEN_SECRET_KEY: "${ACTUAL_NG_KEY}"

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1999
        runAsGroup: 1999

    persistence:
      data:
        existingClaim: *app

    service:
      app:
        controller: *app
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: cash-multiple
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
