---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app actual
spec:
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 15m
  values:
    controllers:
      main:
        enabled: true
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        replicas: 1

        pod:
          enableServiceLinks: false
          securityContext:
            runAsUser: &context 1999
            runAsGroup: *context
            fsGroup: *context
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          main:
            image:
              repository: ghcr.io/actualbudget/actual-server
              tag: 24.10.1
            env:
              TZ: "Europe/London"
              PORT: &port 5006
              TINI_SUBREAPER: 1
              ACTUAL_NORDIGEN_SECRET_ID: "${ACTUAL_NG_ID}"
              ACTUAL_NORDIGEN_SECRET_KEY: "${ACTUAL_NG_KEY}"

            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /status
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false

            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL

    persistence:
      config:
        enabled: true
        existingClaim: actual
        advancedMounts:
          main:
            main:
              - path: /data
    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: cash-multiple
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
