---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: actual
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: volsync
  values:
    image:
      repository: jlongster/actual-server
      tag: 23.10.0-alpine@sha256:adb8ec92c93c383872d2d9c32205da603dfa8109853dc0b9244d2403493797cc

    env:
      PORT: "5006"
      TINI_SUBREAPER: 1
      ACTUAL_NORDIGEN_SECRET_ID: "${ACTUAL_NG_ID}"
      ACTUAL_NORDIGEN_SECRET_KEY: "${ACTUAL_NG_KEY}"

    service:
      main:
        ports:
          http:
            port: 5006

    ingress:
      main:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: cash-multiple
        hosts:
          - host: &host "actual.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      data:
        enabled: true
        existingClaim: actual
        mountPath: /data
