ansible_become_pass: ENC[AES256_GCM,data:Ngoj/kUs,iv:TOLVJRU3fe21rawcG9r/AG3IQolAqmI/gsvDI+Vqrno=,tag:Y1VgkTnuuxWqIqWoiLlZ3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clag278hh0knsesvzqw0rnp6y5tzf2jh3ew937ws2kek66quxpzq86xtqq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVk9BN1lsLzNjeEl3THBJ
            WG93VFBtamIyQ05qTHduZkc1VEU3ajQvV0FrCnZvRDhqZ3BITTZ0dUQ0SzNMNTg4
            czNmcjNaeWpFci90eG1sWHRVLzlPRlEKLS0tIFBMOVJXOTYvajZJd1NKSlJKcEJF
            QjFTNFJSZ3hFcjFDRjUrR3ZKWW9Fd1EKeHqo8d/OAdpzN1I6rOJlPSTNHdZlRXOI
            KTzOZL0CS1IBJnt4zWiDKpbtRI1p8uAjd3wHkLigs5tdRtqIj3a7Ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-07T10:28:52Z"
    mac: ENC[AES256_GCM,data:q4DVl5CB4LPgj6wdJI/X5bhpiPXi8MIdjNW7Y43E35ha3v1f6PRBgxZe8xZTnqoZGVvFUsKPh7iOOJe2r8s3fPpxTxITw0poiC51TY6OouohK24i/H/bOcZ4BisOatOtkjMTWEDnsWWzxC2FcuQTe7HO5YVgE5skGOGstT+A7YQ=,iv:96WNgenqvA/XutYW8otYQMQzqLWnQKJtOrOxWV6XmJY=,tag:ktCAEWA2wqMiy1xhCFDhzA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
