---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/nfd.k8s-sigs.io/nodefeaturerule_v1alpha1.json
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: ups-apc-device
spec:
  rules:
    - name: ups.apc
      labels:
        ups.feature.node.kubernetes.io/apc: "true"
      matchFeatures:
        - feature: usb.device
          matchExpressions:
            vendor: { op: In, value: ["051d"] }
            device: { op: In, value: ["0002"] }
