---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: hass-config-restore
spec:
  trigger:
    manual: restore-once
  restic:
    repository: home-assistant-restic-nas-secret
    # Use an existing PVC, don't provision a new one
    destinationPVC: home-assistant-config
    copyMethod: Direct
    storageClassName: ceph-filesystem
    restoreAsOf: "2023-12-22T23:59:59-00:00"
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"

