---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jupyter
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    controllers:
      jupyter:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: jupyter/base-notebook
              tag: latest
            args:
              - jupyter
              - notebook
              - --ip=0.0.0.0
    service:
      app:
        controller: jupyter
        ports:
          http:
            port: 8888
    ingress:
      app:
        annotations:
          auth.home.arpa/enabled: "true"
        className: internal
        hosts:
          - host: "jupyter.monkeysrus.uk"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        existingClaim: zigbee2mqtt
