---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: node-red-restore
spec:
  trigger:
    manual: restore-once
  restic:
    repository: node-red-restic-secret
    # Use an existing PVC, don't provision a new one
    destinationPVC: node-red
    copyMethod: Direct
    storageClassName: ceph-block
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: "OnRootMismatch"

