---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: omada-work-nas
spec:
  trigger:
    manual: restore-once
  restic:
    repository: omada-work-restic-nas-secret
    # Use an existing PVC, don't provision a new one
    destinationPVC: omada-work
    copyMethod: Direct
    storageClassName: ceph-block
    restoreAsOf: "2023-12-22T23:59:59-00:00"
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: omada-data-nas
spec:
  trigger:
    manual: restore-once
  restic:
    repository: omada-data-restic-nas-secret
    # Use an existing PVC, don't provision a new one
    destinationPVC: omada-data
    copyMethod: Direct
    storageClassName: ceph-block
    restoreAsOf: "2023-12-22T23:59:59-00:00"
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: omada-logs-nas
spec:
  trigger:
    manual: restore-once
  restic:
    repository: omada-logs-restic-nas-secret
    # Use an existing PVC, don't provision a new one
    destinationPVC: omada-logs
    copyMethod: Direct
    storageClassName: ceph-block
    restoreAsOf: "2023-12-22T23:59:59-00:00"
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
