---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: tautulli-restore
spec:
  trigger:
    manual: restore-once
  restic:
    repository: tautulli-volsync-secret-minio
    # Use an existing PVC, don't provision a new one
    destinationPVC: tautulli
    copyMethod: Direct
    storageClassName: ceph-block
    restoreAsOf: "2023-12-22T23:59:59-00:00"
    moverSecurityContext:
      runAsUser: 1999
      runAsGroup: 1999
      fsGroup: 1999
      fsGroupChangePolicy: "OnRootMismatch"

