---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: zigbee2mqtt-restore
spec:
  trigger:
    manual: restore-once
  restic:
    repository: zigbee2mqtt-restic-nas-secret
    # Use an existing PVC, don't provision a new one
    destinationPVC: zigbee2mqtt
    copyMethod: Direct
    storageClassName: ceph-block
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
      fsGroupChangePolicy: "OnRootMismatch"

