---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: zigbee2mqtt-restic-secret
  namespace: default
  labels:
    app.kubernetes.io/name: zigbee2mqtt
type: Opaque
stringData:
  RESTIC_REPOSITORY: ${SECRET_RESTIC_S3_REPO}/zigbee2mqtt
  RESTIC_PASSWORD: ${SECRET_RESTIC_PASSWORD}
  AWS_ACCESS_KEY_ID: ${SECRET_RESTIC_S3_KEY}
  AWS_SECRET_ACCESS_KEY: ${SECRET_RESTIC_S3_PASS}
  RESTIC_PACK_SIZE: "60"
---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: zigbee2mqtt
  namespace: default
spec:
  sourcePVC: zigbee2mqtt
  trigger:
    schedule: 0 2 * * *
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 7
    repository: zigbee2mqtt-restic-secret
    cacheCapacity: 8Gi
    cacheStorageClassName: local-path
    volumeSnapshotClassName: csi-ceph-blockpool
    storageClassName: ceph-block
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    retain:
      daily: 7
      within: 3d
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: zigbee2mqtt-restic-nas-secret
  namespace: home
  labels:
    app.kubernetes.io/name: zigbee2mqtt
type: Opaque
stringData:
  RESTIC_REPOSITORY: s3:http://minio.default.svc.cluster.local:9000/restic-home-cluster/zigbee2mqtt
  RESTIC_PASSWORD: ${SECRET_RESTIC_PASSWORD}
  AWS_ACCESS_KEY_ID: ${SECRET_NAS_MINIO_ACCESS_KEY}
  AWS_SECRET_ACCESS_KEY: ${SECRET_NAS_MINIO_SECRET_KEY}
  RESTIC_PACK_SIZE: "60"
---
# yaml-language-server: $schema=https://schemas.budimanjojo.com/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: zigbee2mqtt-nas
  namespace: default
spec:
  sourcePVC: zigbee2mqtt
  trigger:
    schedule: "0 */6 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 7
    repository: zigbee2mqtt-restic-nas-secret
    cacheCapacity: 8Gi
    cacheStorageClassName: local-path
    volumeSnapshotClassName: csi-ceph-blockpool
    storageClassName: ceph-block
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    retain:
      daily: 7
      within: 3d
