---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app pgadmin
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: dpage/pgadmin4
              tag: 7.8
            envFrom:
              - secretRef:
                  name: pgadmin-secret
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        className: internal
        hosts:
          - host: &host pgadmin.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    defaultPodOptions:
      securityContext:
        runAsUser: 5050
        runAsGroup: 5050
        fsGroup: 5050
        fsGroupChangePolicy: "OnRootMismatch"
    persistence:
      config:
        enabled: true
        existingClaim: pgadmin-config
        globalMounts:
          - path: /var/lib/pgadmin
      server-json:
        enabled: true
        type: configMap
        name: servers-json
        subPath: servers.json
        globalMounts:
          - path: /pgadmin4/servers.json
    podAnnotations:
      secret.reloader.stakater.com/reload: *app
