---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - config-pvc.yaml
  - secret.sops.yaml
  - helm-release.yaml
configMapGenerator:
  - name: servers-json
    files:
      - config/servers.json
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
