apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-secret
    namespace: default
type: Opaque
stringData:
    PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:yVmmSxH+a+hmiAiCAzFYJSjfUQMY,iv:2QUGGFbJb0TWpioe528WSuf82pyrhkTJwAASYI9K7dQ=,tag:k2vDGDVL7yp0Iond3BOLoQ==,type:str]
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:srffVvydKbUaUzDw,iv:ReaOXtEC9URWvo2QuA5FsbBpekVPCaw3mUyhHeKlI3E=,tag:+/qfj30WukFbsQaphIE9ug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clag278hh0knsesvzqw0rnp6y5tzf2jh3ew937ws2kek66quxpzq86xtqq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NElIVzlla0VadlFXUDNQ
            MEhucWJKclpLcGdKVTk1dUVJTTJzbzF6RGpZClNsd0tGcG5zdXhMWlVTNmhUQ2w1
            eGFWS3FRM1c0RWd4YWtGNm9uK3VXZDAKLS0tICt1dFA1azQ0bXVNQzZabmY2Njda
            R3B0anVWN3d6cmgwdW02a2NWWEJHUDAK53lb9NxVUQRIlwr0kpK4oRAoz75AUrty
            7qr95RkRoeW+66w7PUd5UypvQvs5Kkw1MDnY4ANXaYbkel/rGMhrJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-13T22:05:10Z"
    mac: ENC[AES256_GCM,data:JqA1hzHpSi9quUEV+AAu0iGz++HK2rkV9dfguRxBsZXRKSRfH/NCOThqyyoT1SvAvMqQ2U3oHlpN/bnMMhiZ1NoCTrStaGByjtWVU/GLBUJOeCWzfgOsh5VThyedKJ4W51X5bkNrll2wbmGX1EPQzyt3DiDua3ZgfDK1IqIKTvI=,iv:2A3954M7Wvw7tKZSqBTyN2a+vTyILY58Kd1UKAO+ds4=,tag:n9nB/ysAFzAsykPPb4vA/Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
