---
apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg
  namespace: default
type: Opaque
stringData:
  username: ${SECRET_CNPG_SUPER_USER}
  password: ${SECRET_CNPG_SUPER_PASS}
  S3_ACCESS_KEY: ${SECRET_CNPG_S3_ACCESS_KEY}
  S3_SECRET_KEY: ${SECRET_CNPG_S3_SECRET_KEY}
