apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:n8xnw4DSVg+9pGdoUdl9De7c4ZUkWmeM5Z4AzFnqBdLYBka5N/Sj9w==,iv:8bFd9ATAN3RXiOOciIMLG5saXGnOjDINOWMO5YD4fHA=,tag:8X5EFBYieThXS6MMFiqrWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clag278hh0knsesvzqw0rnp6y5tzf2jh3ew937ws2kek66quxpzq86xtqq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQjRhMXY3RFVwQ3NZdWhv
            VFhMY3NteG1oYVhRb29rc2tMUmZpNlJVdDN3CmpoUUtqbGdENWNVQ2pYNVVPYVF3
            Q2J4UENtaUhqVm9tWkY1NCtWWDh4aEUKLS0tIE5lYW5BYllhZ01uUGluS1FyemlR
            OVI2cG9iZFZGU1VqVTR6YU4vNUROSk0KIjfLtI4zmn1X4633dS8OVt4jB92BDAE5
            ApCYOSxdiBrrlt0W321CZDk6md8pkxrEVmkPeGUnV1+sDbFWMG+SBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-07T10:29:38Z"
    mac: ENC[AES256_GCM,data:Y/m3zadqeJbCMKFYAK8oUtOx6WFZWYm8COJvQahCdGdRgAMugk2fo5HLqquQo7wFhBQ3az+E3Yrs1lv79kRbGqRSNMRap8ANR1aS8nO78biKcCiW23HJBE30F+NBsX0SZ9Tv9TQmUaOZlV89sZ7VmFUGhLH9mklfCqWjlUhgYzQ=,iv:5b1Wfla2cxyYnYpy28Xyrdyy1NetjslHCmE+XaPr15k=,tag:IAp6BFlyuG+i28JKU+FK+A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
