apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:YEfeNkJq1gVBeSGd,iv:Lj6ig0/Ww/oGa4yneu6k0VvAhedqkl4spIQ4xmyLiK0=,tag:JrCV70wQvB3n9EbC3PFkSw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clag278hh0knsesvzqw0rnp6y5tzf2jh3ew937ws2kek66quxpzq86xtqq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWYW1SU0Y0S0x6RVNNMklw
            MjBCOTVzY2d0NTJsNUU2WkNyMWZUcDJMSWlVCkVvZVhSMSt1WVR1dDNiWHNHQllB
            Z3dNTUc1dmN3eDlQUXlTZE9NaGxQUk0KLS0tIFcvdytlR0hvc0o1VTFGNmZpVUJU
            cUVxN3RreC9mMWNQdk5jYlQxZFc0eHMKaPHDXItOnfMcSF2YGpZTPmmElBtbysve
            Re+Tmmvtatf9XrKI09/IHJQYB84GScZzQF78NLgJpQRgi08j0bYngw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-07T10:29:39Z"
    mac: ENC[AES256_GCM,data:pCJNgdIj6/4DKYR39kgPFCJBE/ynSX6MEOo7Wbd54vMVurBR+c7Utg7nQqEM1GT6q9/JKOR0I7jZYYFyobj47R7zn6qVAEiuGZlD7CTvAlF1w7xmIe088ekmZi6C9QYootSPjulDNsiS8kTYFJgW9Py+1a+iMA0UssNHNjdq47A=,iv:7qUNC7aUhmmvVqsBpXGwSSY00n5onEh2Wz/ainEoJbo=,tag:ZK2X9KyiUeodFQcycStW1A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
