---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings-user
  namespace: flux-system
data:
  SVC_OMADA_CONTROLLER: "192.168.167.213"
  SVC_EMQX_IP: "192.168.167.214"
  SVC_PLEX_IP: "192.168.167.215"
