apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:Ce0UfcHWIOEuF4V1I3PH2xwBIDVuMkziKQ==,iv:oNyIuo2G4k3gv6cLMDBTc7YrpxA13z4iRq3eRVrGPcY=,tag:G9vvs/Qo/Piqk4PwfRfsvQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:X+BHjWFYjK31NGEDrGCCcvEDpRDQixwG4y9wDUoYQxwYACQy,iv:1R8ECpu57ZSYL2J7B2YrcC05yJCAp1M6fAfPYn5f0uM=,tag:Zflc6bhCmj9jMBnQRQDx8g==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:6pkUnb8cg0Z0n5cAYQ==,iv:BP8QXaXZyG82wU7cTvPupLvOYeHPeJLLv5ze2RBLANw=,tag:7FNUBXd6GKpMTIJVm3GtVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clag278hh0knsesvzqw0rnp6y5tzf2jh3ew937ws2kek66quxpzq86xtqq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzQzB6UTd4ZFY5WVlLU3lu
            bEg3c2FSMVg4d3dFTktrbkNUS1RseXl6MEN3CllTQUtFUU5reC85MHFhVGFrRW9X
            NWJUUU81LzZ3Tk5MdTJuL0NKQ0IzRTAKLS0tIFpNSDR6ZzgyWitqRWVFMUpaRmla
            bnBQV2Qwd01YWDNhWkpjZzVETEhyRlEKzQY32EUPu7zrykadpmEE3K5D3evHAEjq
            D6cKYpZM76CEqC92qflwJ182aFuusGsfa2UHHo51G87Ni38fZaU/bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-07T10:29:39Z"
    mac: ENC[AES256_GCM,data:hz5Nux56iYk71k52OaUliRjsTdmG32Rsomtfq9Wussk2R44ZaKpedjkZoCP6I16QivNtDRQLy29tnyTFFLkPZ99Yt/PgQN669E8qXqv5TorUqmQORNHGZzOkbFhwY6fFTRLOBKG07RxrvtJLIs89/R5OW2Zz4LQz44N63Ufbq04=,iv:Fm45YiiTbjGkgD09jzmSzo5yd1T5cg5hV8xHRbeDVYg=,tag:u9q7XhaA7bu27XYM3Qo+Yg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
