---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
spec:
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          enableServiceLinks: false
          nodeSelector:
            intel.feature.node.kubernetes.io/gpu: "true"
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 44
              - 109
              - 1001

        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/plex
              tag: 1.32.8.7639-fb6452ebf@sha256:97bf4a8eac34de4b0df78e4fc3e2b501187161a3a264fa2b220bd51b0f89ba77
            resources:
              requests:
                # cpu: 100m
                gpu.intel.com/i915: 1
                # memory: 9248M
              limits:
                gpu.intel.com/i915: 1
                # memory: 9248M

    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          io.cilium/lb-ipam-ips: ${SVC_PLEX_IP}
        ports:
          http:
            port: 32400

    ingress:
      main:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
          nginx.ingress.kubernetes.io/backend-protocol: HTTPS
        className: internal
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: plex
        advancedMounts:
          main:
            main:
              - path: /config
      transcode:
        type: emptyDir
      tmp:
        type: emptyDir
      nfs-movies:
        type: nfs
        server: "${NAS_SERVER}"
        path: "/mnt/Vol1/Movies"
        advancedMounts:
          main:
            main:
              - path: /media-movies
      nfs-cfmovies:
        type: nfs
        server: "${NAS_SERVER}"
        path: "/mnt/Vol1/CFMovies"
        advancedMounts:
          main:
            main:
              - path: /media-cfmovies
      nfs-cftvshows:
        type: nfs
        server: "${NAS_SERVER}"
        path: "/mnt/SG6TB/CFTVShows"
        advancedMounts:
          main:
            main:
              - path: /media-cftvshows
      nfs-tvshows:
        type: nfs
        server: "${NAS_SERVER}"
        path: "/mnt/SG6TB/TVShows"
        advancedMounts:
          main:
            main:
              - path: /media-tvshows
