---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-videos
spec:
  capacity:
    storage: 1Ti
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.167.5
    path: "/mnt/SG6TB2/Data/Home Videos"
  mountOptions:
    - nfsvers=3
    - nconnect=8
    - hard
    - noatime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-videos
  namespace: default
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Ti
