---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omada-data
  namespace: default
  labels:
    app.kubernetes.io/name: omada-data
    app.kubernetes.io/instance: omada
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omada-work
  namespace: default
  labels:
    app.kubernetes.io/name: omada-work
    app.kubernetes.io/instance: omada
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omada-logs
  namespace: default
  labels:
    app.kubernetes.io/name: omada-logs
    app.kubernetes.io/instance: omada
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block
