---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: &name home-assistant-config
  namespace: default
  labels:
    app.kubernetes.io/name: *name
    app.kubernetes.io/instance: *name
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-filesystem
