---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    controllers:
      home-assistant:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          hostNetwork: true
          securityContext:
            runAsUser: 0 # Change when starting from scratch
            runAsGroup: 568
            runAsNonRoot: false # Change when starting from scratch
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch

        containers:
          app:
            image:
              repository: ghcr.io/home-assistant/home-assistant
              tag: 2025.7.2
            env:
              TZ: Europe/London
              POSTGRES_HOST: hass-psql-v16-1-rw.default.svc.cluster.local
              POSTGRES_DB: home_assistant
            envFrom:
              - secretRef:
                  name: home-assistant-secret
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false

            resources:
              requests:
                cpu: 100m
                memory: 128Mi
              limits:
                memory: 1Gi

          code-server:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.104.2
            args:
              [
                "--auth",
                "none",
                "--disable-telemetry",
                "--disable-update-check",
                "--user-data-dir",
                "/config/.vscode",
                "--extensions-dir",
                "/config/.vscode",
                "--port",
                "8080",
                "/config",
              ]

            env:
              TZ: Europe/London
              # HASS_SERVER: http://localhost:8123
              # HASS_TOKEN:
              #   valueFrom:
              #     secretKeyRef:
              #       name: home-assistant-secret
              #       key: VSCODE_TOKEN

            resources:
              requests:
                cpu: 10m
                memory: 100M
              limits:
                memory: 500M

    service:
      app:
        controller: home-assistant
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          io.cilium/lb-ipam-ips: "${SVC_HASS_IP}"
        ports:
          http:
            port: 8123
          code-server:
            port: 8080

    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          hajimari.io/icon: mdi:home-assistant
        hosts:
          - host: "hass.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

      code-server:
        enabled: true
        className: internal
        annotations:
          hajimari.io/icon: cib:visual-studio-code
        hosts:
          - host: "hass-vs.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: code-server

    persistence:
      config:
        existingClaim: home-assistant-config


      # https://community.home-assistant.io/t/wth-is-going-on-with-docker-container-installs-and-third-party-integrations-that-need-python-modules/806430/6
      hack:
        type: emptyDir
        advancedMounts:
          home-assistant:
            app:
              - path: /.dockerenv
                subPath: .dockerenv
