---
apiVersion: v1
kind: Secret
metadata:
  name: home-assistant-secret
  namespace: default
type: Opaque
stringData:
  HASS_POSTGRES_URL: "postgresql://${SECRET_CNPG_SUPER_USER}:${SECRET_CNPG_SUPER_PASS}@hass-psql-v16-rw.default.svc.cluster.local/home_assistant"
  # Postgres Init
  INIT_POSTGRES_DBNAME: home_assistant
  INIT_POSTGRES_HOST: hass-psql-v16-rw.default.svc.cluster.local
  INIT_POSTGRES_USER: ${SECRET_CNPG_SUPER_USER}
  INIT_POSTGRES_PASS: ${SECRET_CNPG_SUPER_PASS}
  INIT_POSTGRES_SUPER_PASS: ${SECRET_CNPG_SUPER_PASS}
