---
apiVersion: v1
kind: Secret
metadata:
  name: home-assistant-secret
  namespace: default
type: Opaque
stringData:
  HASS_POSTGRES_URL: "postgresql://hass:${SECRET_CNPG_HASS_APP_PASS}@psql-v16-2-rw.default.svc.cluster.local/hass"
  # Postgres Init
  INIT_POSTGRES_DBNAME: hass
  INIT_POSTGRES_HOST: psql-v16-2-rw.default.svc.cluster.local
  INIT_POSTGRES_USER: hass
  INIT_POSTGRES_PASS: ${SECRET_CNPG_HASS_APP_PASS}
  INIT_POSTGRES_SUPER_PASS: ${SECRET_CNPG_SUPER_PASS}
