---
apiVersion: v1
kind: Secret
metadata:
  name: home-assistant-secret
  namespace: default
type: Opaque
stringData:
  HASS_POSTGRES_URL: "postgresql://app:${SECRET_CNPG_HASS_APP_PASS}@hass-psql-v16-1-rw.default.svc.cluster.local/app"
  # Postgres Init
  INIT_POSTGRES_DBNAME: app
  INIT_POSTGRES_HOST: hass-psql-v16-1-rw.default.svc.cluster.local
  INIT_POSTGRES_USER: app
  INIT_POSTGRES_PASS: ${SECRET_CNPG_HASS_APP_PASS}
  INIT_POSTGRES_SUPER_PASS: ${SECRET_CNPG_SUPER_PASS}
